apiVersion: v1
kind: Service
metadata:
  name: irmgard-service
spec:
  type: LoadBalancer
  selector:
    app: irmgard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # TODO sollte hier nicht der Port von irmgard depl stehen, also 80?
