apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: "minio"
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          # Latest stable version from dockerhub as of 06.08.2023
          # Some versions were resulting in compatibility problems with MacOS (although "stable")
          image: minio/minio:RELEASE.2023-08-04T17-40-21Z.hotfix.04968f7ec
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_SECRET_KEY
          volumeMounts:
            - name: minio-persistent-volume-claim
              mountPath: /data
      volumes:
        - name: minio-persistent-volume-claim
          persistentVolumeClaim:
            claimName: minio-persistent-volume-claim
