apiVersion: v1
kind: Service
metadata:
  name: minio-primary
  labels:
    app: minio
    role: primary
spec:
  clusterIP: None
  selector:
    app: minio
    role: primary
  ports:
  - port: 9000
    name: minio-primary-port