apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  clusterIP: None
  selector:
    app: minio
    role: primary
  ports:
    - port: 9000
      name: minio-port
      targetPort: 9000
