apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  clusterIP: None
  selector:
    app: postgres
    role: primary
  ports:
    - port: 5432
      name: postgres-port
      targetPort: 5432
