apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  clusterIP: None
  selector:
    app: rabbitmq
    role: primary
  ports:
    - port: 5672
      name: rabbitmq-amqp-p
      targetPort: 5672
